### ISSUE TITLE
Adjustment to criminal DT

### ISSUE THREAD

**Issue by rylock890** [1drturtle/Avrae-Aliases#12]
**Alias Name**: DT-Crime

**Alias Functionality**: To add Modifiers to the crime DT

**Why?**: To allow outside sources to influence the rolls. Examples as such are the spell Pass without a trace, give a +10 to stealth. Gloves of thievery give a +5 to sleight of hand and so forth.

**Additional Notes** (Optional): None

**Comment by rylock890** [comment]
Or add the guidance spell 1d4 as well.

**Comment by 1drturtle** [comment]
Request for @mrrobinhood5 
Add bonuses for each stat, like `-sb`, `-cb` etc so we can add generic bonuses.

**Comment by mrrobinhood5** [comment]
PR #14 created to address this
