### ISSUE TITLE
Passives in Downtime

### ISSUE THREAD

**Issue by Ithala** [1drturtle/Avrae-Aliases#13]
**Alias Name**: Downtime Aliases

**Alias Functionality**: Check or calculate Passives for checks that allow passive and uses the highest passive in place of the appropriate check if it would allow the check to pass

**Why?**: Would give players a guaranteed pass on some downtimes (the ones with multiple checks where at least one check doesn't incur a penalty for rolling low)

**Additional Notes** (Optional):

**Comment by 1drturtle** [comment]
So, use the highest passive?
Or use the passive on the highest score that will pass?
Or maybe an argument?

**Comment by mrrobinhood5** [comment]
assign @mrrobinhood5
